### ISSUE TITLE
User Flags show EARLY_VERIFIED_BOT_OWNER, but it should be EARLY_VERIFIED_DEVELOPER

### ISSUE THREAD

**Issue by RobinSchapendonk** [discordjs/website#59] opened 2021-05-12 16:47 UTC
https://discord.com/channels/222078108977594368/223867697312694272/842079569941889085

**Comment by Dev-CasperTheGhost** [comment] 2021-05-12 17:06
This is a duplicate of discordjs/discord.js#5102. I'm pretty sure this is fixed in the [master](https://github.com/discordjs/discord.js/tree/master) branch

**Closed** 2021-05-12 18:29 UTC
Labels: invalid
